trigger:
  - main

steps:
  - script: |
      echo 'second pipeline run parallel with first pipeline'
      echo '$(Build.Repository.ID)'
      commitID=$(git rev-parse --short HEAD)
      echo $commitID 
    displayName: Second